name: Update Rules

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: 

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Fetch OpenAi.list
      run: |
        curl -o Rules/Clash\ Meta/OpenAi.list https://raw.githubusercontent.com/LM-Firefly/Rules/refs/heads/master/PROXY/OpenAI.list
        cp Rules/Clash\ Meta/OpenAi.list Rules/Shadowrocket/OpenAi.list

    - name: Fetch YouTube.list
      run: |
        curl -o Rules/Clash\ Meta/YouTube.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list
        cp Rules/Clash\ Meta/YouTube.list Rules/Shadowrocket/YouTube.list

    - name: Fetch YouTubeMusic.list
      run: |
        curl -o Rules/Clash\ Meta/YouTubeMusic.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTubeMusic/YouTubeMusic.list
        cp Rules/Clash\ Meta/YouTubeMusic.list Rules/Shadowrocket/YouTubeMusic.list

    - name: Fetch Twitch.list
      run: |
        curl -o Rules/Clash\ Meta/Twitch.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Twitch/Twitch.list
        cp Rules/Clash\ Meta/Twitch.list Rules/Shadowrocket/Twitch.list

    - name: Fetch Disney.list
      run: |
        curl -o Rules/Clash\ Meta/Disney.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Disney/Disney.list
        cp Rules/Clash\ Meta/Disney.list Rules/Shadowrocket/Disney.list

    - name: Fetch TikTok.list
      run: |
        curl -o Rules/Clash\ Meta/TikTok.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
        cp Rules/Clash\ Meta/TikTok.list Rules/Shadowrocket/TikTok.list

    - name: Fetch Netflix.list
      run: |
        curl -o Rules/Shadowrocket/Netflix.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
        cp Rules/Shadowrocket/Netflix.list Rules/Clash\ Meta/Netflix.list
        sed -i 's/USER-AGENT/IN-USER/g' Rules/Clash\ Meta/Netflix.list
        sed -i '/URL-REGEX/d' Rules/Clash\ Meta/Netflix.list     

    - name: Fetch Spotify.list
      run: |
        curl -o Rules/Clash\ Meta/Spotify.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Spotify/Spotify.list
        cp Rules/Clash\ Meta/Spotify.list Rules/Shadowrocket/Spotify.list

    - name: Fetch Twitter.list
      run: |
        curl -o Rules/Clash\ Meta/Twitter.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Twitter/Twitter.list   
        cp Rules/Clash\ Meta/Twitter.list Rules/Shadowrocket/Twitter.list

    - name: Fetch GoogleFCM.list
      run: |
        curl -o Rules/Clash\ Meta/GoogleFCM.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
        cp Rules/Clash\ Meta/GoogleFCM.list Rules/Shadowrocket/GoogleFCM.list

    - name: Fetch Google.list
      run: |
        curl -o Rules/Clash\ Meta/Google.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/293afd1572e97a1d6adbaee34050868d696e3e08/rule/Clash/Google/Google.list
        cp Rules/Clash\ Meta/Google.list Rules/Shadowrocket/Google.list

    - name: Fetch PrivateTracker.list
      run: |
        curl -o Rules/Clash\ Meta/PrivateTracker.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/293afd1572e97a1d6adbaee34050868d696e3e08/rule/Clash/PrivateTracker/PrivateTracker.list
        cp Rules/Clash\ Meta/PrivateTracker.list Rules/Shadowrocket/PrivateTracker.list

    - name: Fetch Bing.list
      run: |
        curl -o Rules/Clash\ Meta/Bing.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
        cp Rules/Clash\ Meta/Bing.list Rules/Shadowrocket/Bing.list

    - name: Fetch Microsoft.list
      run: |
        curl -o Rules/Clash\ Meta/Microsoft.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list
        cp Rules/Clash\ Meta/Microsoft.list Rules/Shadowrocket/Microsoft.list

    - name: Fetch MicrosoftCDN.conf
      run: |
        curl -o Rules/Clash\ Meta/MicrosoftCDN.list https://ruleset.skk.moe/List/non_ip/microsoft_cdn.conf
        cp Rules/Clash\ Meta/MicrosoftCDN.list Rules/Shadowrocket/MicrosoftCDN.list

    - name: Fetch Apple.list
      run: |
        curl -o Rules/Clash\ Meta/Apple.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
        cp Rules/Clash\ Meta/Apple.list Rules/Shadowrocket/Apple.list

    - name: Fetch AppleCDN.conf
      run: |
        curl -o Rules/Clash\ Meta/AppleCDN.list https://ruleset.skk.moe/List/non_ip/apple_cdn.conf
        cp Rules/Clash\ Meta/AppleCDN.list Rules/Shadowrocket/AppleCDN.list

    - name: Fetch Epic.list
      run: |
        curl -o Rules/Clash\ Meta/Epic.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
        cp Rules/Clash\ Meta/Epic.list Rules/Shadowrocket/Epic.list

    - name: Fetch Origin.list
      run: |
        curl -o Rules/Clash\ Meta/Origin.list https://raw.githubusercontent.com/LM-Firefly/Rules/refs/heads/master/Game/EA.list
        cp Rules/Clash\ Meta/Origin.list Rules/Shadowrocket/Origin.list

    - name: Fetch Nintendo.list
      run: |
        curl -o Rules/Clash\ Meta/Nintendo.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
        cp Rules/Clash\ Meta/Nintendo.list Rules/Shadowrocket/Nintendo.list

    - name: Fetch Sony.list
      run: |
        curl -o Rules/Clash\ Meta/Sony.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
        cp Rules/Clash\ Meta/Sony.list Rules/Shadowrocket/Sony.list
    
    - name: Fetch Xbox.list
      run: |
        curl -o Rules/Clash\ Meta/Xbox.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Xbox/Xbox.list
        cp Rules/Clash\ Meta/Xbox.list Rules/Shadowrocket/Xbox.list

    - name: Fetch Ubisoft.list
      run: |
        curl -o Rules/Clash\ Meta/Ubisoft.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/UBI/UBI.list
        cp Rules/Clash\ Meta/Ubisoft.list Rules/Shadowrocket/Ubisoft.list

    - name: Fetch Rockstar.list
      run: |
        curl -o Rules/Clash\ Meta/Rockstar.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Rockstar/Rockstar.list
        cp Rules/Clash\ Meta/Rockstar.list Rules/Shadowrocket/Rockstar.list

    - name: Fetch ProxyGFWlist.list
      run: |
        curl -o Rules/Clash\ Meta/ProxyGFWlist.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
        cp Rules/Clash\ Meta/ProxyGFWlist.list Rules/Shadowrocket/ProxyGFWlist.list

    - name: Fetch global.txt
      run: |
        curl -o Rules/Clash\ Meta/Global.list https://ruleset.skk.moe/Clash/non_ip/global.txt
        cp Rules/Clash\ Meta/Global.list Rules/Shadowrocket/Global.list

    - name: Fetch ChinaDomain.list
      run: |
        curl -o Rules/Clash\ Meta/ChinaDomain.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
        cp Rules/Clash\ Meta/ChinaDomain.list Rules/Shadowrocket/ChinaDomain.list

    - name: Fetch ChinaCompanyIp.list
      run: |
        curl -o Rules/Clash\ Meta/ChinaCompanyIp.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
        cp Rules/Clash\ Meta/ChinaCompanyIp.list Rules/Shadowrocket/ChinaCompanyIp.list

    - name: Fetch Download.list
      run: |
        curl -o Rules/Shadowrocket/Download.list https://raw.githubusercontent.com/LM-Firefly/Rules/refs/heads/master/Special/Download.list
        cp Rules/Shadowrocket/Download.list Rules/Clash\ Meta/Download.list

    - name: Fetch LocalAreaNetwork.list
      run: |
        curl -o Rules/Clash\ Meta/LocalAreaNetwork.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
        cp Rules/Clash\ Meta/LocalAreaNetwork.list Rules/Shadowrocket/LocalAreaNetwork.list

    - name: Fetch and Process GoogleCN.list
      run: |
        # 下载原始dnsmasq格式的文件
        curl -o google.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/refs/heads/master/google.china.conf
        
        # 转换格式: server=/265.com/114.114.114.114 -> DOMAIN-SUFFIX,265.com
        sed -n 's/^server=\/\(.*\)\/114.114.114.114$/DOMAIN-SUFFIX,\1/p' google.china.conf > Rules/Clash\ Meta/GoogleCN.list
        
        cp Rules/Clash\ Meta/GoogleCN.list Rules/Shadowrocket/GoogleCN.list

    - name: Fetch OneDrive.list
      run: |
        curl -o Rules/Shadowrocket/OneDrive.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OneDrive/OneDrive.list
        cp Rules/Shadowrocket/OneDrive.list Rules/Clash\ Meta/OneDrive.list

    - name: Merge ProxyMedia.list
      run: |
        # 将 Netflix、YouTube、YouTubeMusic、Twitch、Disney、TikTok、Spotify 合并到 ProxyMedia.list
        echo "" > Rules/Clash\ Meta/ProxyMedia.list
        for file in "Netflix" "YouTube" "YouTubeMusic" "Twitch" "Disney" "TikTok" "Spotify"; do
          echo "" >> Rules/Clash\ Meta/ProxyMedia.list
          cat Rules/Clash\ Meta/$file.list >> Rules/Clash\ Meta/ProxyMedia.list
        done
        # 拷贝到 Shadowrocket 路径
        cp Rules/Clash\ Meta/ProxyMedia.list Rules/Shadowrocket/ProxyMedia.list

    - name: Check for changes
      id: check_changes
      run: |
        if git diff --exit-code; then
          echo "changes_detected=false" >> $GITHUB_ENV
        else
          echo "changes_detected=true" >> $GITHUB_ENV
        fi

    - name: Update index.html with current Beijing time
      if: env.changes_detected == 'true'
      run: |
        # Get the current Beijing time
        current_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M')
        # Update the index.html file
        sed -i "s|\(<i class=\"far fa-clock mr-1\"></i> 最后更新:\)[^<]*|\1 $current_time|" index.html

    - name: Commit and push changes
      if: env.changes_detected == 'true'
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add Rules/ index.html
        git commit -m 'Update Rules and Last Update Time'
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
