name: Update Rules

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: 

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Fetch OpenAi.list
      run: curl -o Rules/OpenAi.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list

    - name: Fetch Twitter.list
      run: curl -o Rules/Twitter.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Twitter/Twitter.list   

    - name: Fetch GoogleFCM.list
      run: curl -o Rules/GoogleFCM.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list

    - name: Fetch Google.list
      run: curl -o Rules/Google.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/293afd1572e97a1d6adbaee34050868d696e3e08/rule/Clash/Google/Google.list

    - name: Fetch PrivateTracker.list
      run: curl -o Rules/PrivateTracker.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/293afd1572e97a1d6adbaee34050868d696e3e08/rule/Clash/PrivateTracker/PrivateTracker.list

    - name: Fetch direct.txt
      run: curl -o Rules/Direct.list https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/direct.txt
      
    - name: Fetch Bing.list
      run: curl -o Rules/Bing.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list

    - name: Fetch Microsoft.list
      run: curl -o Rules/Microsoft.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list

    - name: Fetch MicrosoftCDN.conf
      run: curl -o Rules/MicrosoftCDN.list https://ruleset.skk.moe/List/non_ip/microsoft_cdn.conf

    - name: Fetch Apple.list
      run: curl -o Rules/Apple.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list

    - name: Fetch AppleCDN.conf
      run: curl -o Rules/AppleCDN.list https://ruleset.skk.moe/List/non_ip/apple_cdn.conf

    - name: Fetch Epic.list
      run: curl -o Rules/Epic.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list

    - name: Fetch Origin.list
      run: curl -o Rules/Origin.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list

    - name: Fetch Nintendo.list
      run: curl -o Rules/Nintendo.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list

    - name: Fetch Sony.list
      run: curl -o Rules/Sony.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list

    - name: Fetch ProxyGFWlist.list
      run: curl -o Rules/ProxyGFWlist.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list

    - name: Fetch global.txt
      run: curl -o Rules/Global.list https://ruleset.skk.moe/Clash/non_ip/global.txt

    - name: Fetch GoogleCN.list
      run: curl -o Rules/GoogleCN.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list

    - name: Fetch ChinaIp.list
      run: curl -o Rules/ChinaIp.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list

    - name: Fetch ChinaDomain.list
      run: curl -o Rules/ChinaDomain.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list

    - name: Fetch ChinaCompanyIp.list
      run: curl -o Rules/ChinaCompanyIp.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list

    - name: Fetch LocalAreaNetwork.list
      run: curl -o Rules/LocalAreaNetwork.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list

    - name: Fetch OneDrive.list
      run: |
        curl -o Rules/OneDrive.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
        cp Rules/OneDrive.list Rules/Clash\ Meta/OneDrive.list
        sed -i 's/USER-AGENT/IN-USER/g' Rules/Clash\ Meta/OneDrive.list
        sed -i 's/URL-REGEX/DOMAIN-REGEX/g' Rules/Clash\ Meta/OneDrive.list

    - name: Fetch Netflix.list
      run: |
        curl -o Rules/Netflix.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
        cp Rules/Netflix.list Rules/Clash\ Meta/Netflix.list
        sed -i 's/USER-AGENT/IN-USER/g' Rules/Clash\ Meta/Netflix.list
        sed -i 's/URL-REGEX/DOMAIN-REGEX/g' Rules/Clash\ Meta/Netflix.list

    - name: Fetch ProxyMedia.list
      run: |
        curl -o Rules/ProxyMedia.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
        cp Rules/ProxyMedia.list Rules/Clash\ Meta/ProxyMedia.list
        # 删除 # AI 区块
        awk '/^# AI/{flag=1;next}/^#/{flag=0} !flag' Rules/Clash\ Meta/ProxyMedia.list > tmp && mv tmp Rules/Clash\ Meta/ProxyMedia.list
        # 删除 # OpenAi 区块
        awk '/^# OpenAi/{flag=1;next}/^#/{flag=0} !flag' Rules/Clash\ Meta/ProxyMedia.list > tmp && mv tmp Rules/Clash\ Meta/ProxyMedia.list
        sed -i 's/USER-AGENT/IN-USER/g' Rules/Clash\ Meta/ProxyMedia.list
        sed -i 's/URL-REGEX/DOMAIN-REGEX/g' Rules/Clash\ Meta/ProxyMedia.list

    - name: Fetch Download.list
      run: |
        curl -o Rules/Download.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
        cp Rules/Download.list Rules/Clash\ Meta/Download.list
        sed -i 's/USER-AGENT/IN-USER/g' Rules/Clash\ Meta/Download.list
        sed -i 's/URL-REGEX/DOMAIN-REGEX/g' Rules/Clash\ Meta/Download.list

    - name: Check for changes
      id: check_changes
      run: |
        if git diff --exit-code; then
          echo "changes_detected=false" >> $GITHUB_ENV
        else
          echo "changes_detected=true" >> $GITHUB_ENV
        fi

    - name: Update index.html with current Beijing time
      if: env.changes_detected == 'true'
      run: |
        # Get the current Beijing time
        current_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M')
        # Update the index.html file
        sed -i "s|<p>Last Update:.*</p>|<p>Last Update: $current_time</p>|" index.html

    - name: Commit and push changes
      if: env.changes_detected == 'true'
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add Rules/ index.html
        git commit -m 'Update Rules and Last Update Time'
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
