name: Update SmartDNS Domain Rules

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch: 

jobs:
  update-smartdns-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Fetch accelerated-domains.china.conf
      run: |
        curl -o SmartDNS/accelerated-domains.china.txt https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
        sed -i 's/server=\/\(.*\)\/114\.114\.114\.114/\1/' SmartDNS/accelerated-domains.china.txt

    - name: Fetch apple.china.conf
      run: |
        curl -o SmartDNS/apple.china.txt https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf
        sed -i 's/server=\/\(.*\)\/114\.114\.114\.114/\1/' SmartDNS/apple.china.txt

    - name: Fetch google.china.conf
      run: |
        curl -o SmartDNS/google.china.txt https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf
        sed -i 's/server=\/\(.*\)\/114\.114\.114\.114/\1/' SmartDNS/google.china.txt

    - name: Fetch gfw.txt
      run: curl -o SmartDNS/gfw.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt

    - name: Fetch microsoft_cdn.conf
      run: |
        curl -o SmartDNS/microsoft.china.txt https://ruleset.skk.moe/List/non_ip/microsoft_cdn.conf
        sed -i 's/DOMAIN-SUFFIX,//g' SmartDNS/microsoft.china.txt
        sed -i 's/DOMAIN,//g' SmartDNS/microsoft.china.txt

    - name: Check for changes
      id: check_changes
      run: |
        if git diff --exit-code; then
          echo "changes_detected=false" >> $GITHUB_ENV
        else
          echo "changes_detected=true" >> $GITHUB_ENV
        fi

    - name: Update index.html with current Beijing time
      if: env.changes_detected == 'true'
      run: |
        # Get the current Beijing time
        current_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M')
        # Update the index.html file
        sed -i "s|<p>Last Update:.*</p>|<p>Last Update: $current_time</p>|" index.html

    - name: Commit and push changes
      if: env.changes_detected == 'true'
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add SmartDNS/ index.html
        git commit -m 'Update SmartDNS Domain Rules and Last Update Time'
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
